### ISSUE TITLE
bad argument #2 to 'text_range' (start > end)

### ISSUE THREAD

**Issue by macdanny** [jugglerchris/ta-regex#4]
I am trying to do some simple search and replaces to strip all characters up to the appearance of the word "Value" on each line.

An excerpt of the file I'm editing:

```
<ConflictBGColor Value="$E3E3FF"/>
<ConflictFGColor Value="$0000FF"/>
<DiffBGColor Value="-"/>
<DiffFGColor Value="$0000FF"/>
<DisjointFGColor Value="$00FF00"/>
```

My regular expression (typed into the Find box):

```
<.*Value="
```

I leave the Replace box blank because I just want to delete the matching text.

I click Find Next and it correctly finds the first text I want to eliminate.  But when I click Replace it gives me this:

```
...les (x86)\textadept_8.0.win32/modules/textadept\find.lua:279: attempt to index a nil value (field '?')
C:\Users\nekulturny/.textadept/modules/ta-regex\regex_find.lua:20: bad argument #2 to 'text_range' (start > end)
```

I am not sure which code is at fault here, ta-replace or TextAdept itself.  I looked at both of the files in the stack trace and I couldn't figure out what was wrong.  I don't know anything about Lua, though.

What I would REALLY like to do is click Replace All instead.  When I do that, though, TextAdept replaces a lot more than I want it to -- the text it deletes spans many lines.  In fact initially I thought ta-regex was matching text spanning lines and that's why it was deleting so much.  It's only when I tested just clicking the Find Next button that I realized ta-regex is matching the text I want it to.

I would be grateful for any help you can give me.

**Comment by jugglerchris** [comment]
Hi,

Thanks for the report, and sorry for the problem!

It took me a little while to reproduce it, but I think I found it: when doing a find when the cursor was at the end of the buffer, it would try to find from (end buffer + 1) to (end buffer), which resulted in the above error in `regex_find.lua`.  I didn't see the find.lua error, though, so perhaps there's something else.  I think it's two separate errors rather than a stack trace.

I've pushed a fix for that - let me know if that solves your problem.  If not, I might need to ask you to add some extra debug.

Thanks,

Chris

**Comment by macdanny** [comment]
Chris,

I got sucked into a vortex of learning about Lua and LPEG after opening this issue.  I am starting to figure out how this all fits together.  This ta-regex module you wrote is ingenious.  My hat is off to you.

Thanks for the quick turnaround.  I did try your fix and it did seem to help.  And thanks for writing this addon.

## 

Dan
